spellbook.py – Pełna baza czarów i system użytku dla gry Firos: Magic & Magic

spells_data = { "Mag Ognia": [ {"name": "Iskra Żarwena", "level": 1, "type": "ogień", "mana": 10, "power": 15, "description": "Wypuszcza iskrę ognia, która podpala wroga"}, {"name": "Krąg Solca", "level": 2, "type": "ogień", "mana": 15, "power": 22, "description": "Tworzy ognisty krąg zadający obrażenia"}, {"name": "Żar Wilczycy", "level": 3, "type": "ogień", "mana": 18, "power": 26, "description": "Zaklęcie ognistej wilczycy atakujące kilku wrogów"}, {"name": "Słońce Wojny", "level": 4, "type": "ogień", "mana": 21, "power": 30, "description": "Eksplozja ognia na całym polu bitwy"}, {"name": "Zemsta Popiołu", "level": 5, "type": "ogień", "mana": 25, "power": 35, "description": "Silne zaklęcie ognia – zwiększa moc przy niskim HP"}, {"name": "Ogień Czterech Kręgów", "level": 6, "type": "ogień", "mana": 30, "power": 40, "description": "Atakuje 4 cele jednocześnie"}, {"name": "Płomień Smoka", "level": 7, "type": "ogień", "mana": 35, "power": 50, "description": "Smoczy ogień zadający masywne obrażenia"}, {"name": "Spalenie Duszy", "level": 8, "type": "ogień", "mana": 40, "power": 60, "description": "Wysysa życie przez ogień z przeciwnika"}, {"name": "Wieczne Płomienie", "level": 9, "type": "ogień", "mana": 50, "power": 70, "description": "Ogień nie do ugaszenia – efekt trwa kilka tur"}, {"name": "Korona Płomieni", "level": 10, "type": "ogień", "mana": 60, "power": 90, "description": "Ostateczne zaklęcie ognia – niszczy wszystko w polu widzenia"} ], "Mag Lodu": [ {"name": "Szron Dziadosza", "level": 1, "type": "lód", "mana": 9, "power": 12, "description": "Zamraża wroga na chwilę"}, {"name": "Zlodź Opuszcza", "level": 2, "type": "lód", "mana": 11, "power": 16, "description": "Pocisk lodu trafia losowego wroga"}, {"name": "Pazury Zimy", "level": 3, "type": "lód", "mana": 15, "power": 23, "description": "Zimowe pazury szarpią wroga"}, {"name": "Zimowy Krąg", "level": 4, "type": "lód", "mana": 20, "power": 28, "description": "Zamraża pole bitwy spowalniając wszystkich"}, {"name": "Sople Nawii", "level": 5, "type": "lód", "mana": 23, "power": 34, "description": "Wbijające się sople"}, {"name": "Wiatr Buranowy", "level": 6, "type": "lód", "mana": 26, "power": 36, "description": "Wiatr lodu uderza przeciwnika"}, {"name": "Zamieć Przodków", "level": 7, "type": "lód", "mana": 30, "power": 41, "description": "Duchy burz śnieżnych wspierają czar"}, {"name": "Królestwo Mrozu", "level": 8, "type": "lód", "mana": 35, "power": 47, "description": "Zamraża duży obszar"}, {"name": "Sędzia Lodowej Otchłani", "level": 9, "type": "lód", "mana": 40, "power": 55, "description": "Zimowy wyrok śmierci"}, {"name": "Wieczna Zima", "level": 10, "type": "lód", "mana": 50, "power": 70, "description": "Zamienia całą mapę w mroźną otchłań"} ] # Pozostałe klasy do uzupełnienia analogicznie: "Nekromanta", "Alchemik", "Mutant", "Wojownik", "Łucznik", "Wiedzący" }

def get_spells_for_class(class_name): return spells_data.get(class_name, [])

def get_spell_by_name(class_name, spell_name): spells = get_spells_for_class(class_name) return next((spell for spell in spells if spell["name"] == spell_name), None)

def list_all_spells(): return [[cls, spell["name"]] for cls in spells_data for spell in spells_data[cls]]

def spell(class_name, spell_name, player_stats): spell = get_spell_by_name(class_name, spell_name) if not spell: return f"\n❌ Nie znaleziono zaklęcia {spell_name} dla klasy {class_name}." if player_stats.level < spell["level"]: return f"\n⚠️ Poziom zbyt niski by użyć zaklęcia {spell_name}." if player_stats.mana < spell["mana"]: return f"\n💧 Brak many. Potrzeba: {spell["mana"]}, masz: {player_stats.mana}" player_stats.mana -= spell["mana"] return f"\n✨ Użyto zaklęcia {spell["name"]}! Efekt: {spell["description"]} (Moc: {spell["power"]})"

def init_spellbook(): return dict((cls, spells_data[cls]) for cls in spells_data)

